In [1]:
%load_ext lab_black

In [1]:
import json
import requests
import yaml

url = "https://ckan.opendata.swiss/api/3/action/package_show?id=bevolkerung-nach-zivilstand-geschlecht-alter-und-stadtquartier-seit-1993"

resp = requests.get(url)
resp.content[:500]

b'{"help": "https://ckan.opendata.swiss/api/3/action/help_show?name=package_show", "success": true, "result": {"license_title": null, "maintainer": "Open Data Z\\u00fcrich", "issued": "2021-09-30T00:00:00", "title_for_slug": "bevolkerung-nach-zivilstand-geschlecht-alter-und-stadtquartier-seit-1993", "qualified_relations": [], "private": false, "maintainer_email": "opendata@zuerich.ch", "num_tags": 10, "contact_points": [{"email": "opendata@zuerich.ch", "name": "Open Data Z\\u00fcrich"}], "keywords":'

In [2]:
resp.status_code

200

In [3]:
resp.encoding

'utf-8'

In [4]:
json_popul = resp.json()
popul_url = json_popul["result"]["resources"][0]["url"]

In [5]:
import pandas as pd

zurich_popul = pd.read_csv(popul_url)

In [6]:
zurich_popul

,StichtagDatJahr,AlterVSort,AlterVCd,AlterV05Sort,AlterV05Cd,AlterV05Kurz,AlterV10Sort,AlterV10Cd,AlterV10Kurz,AlterV20Sort,...,SexLang,KreisCd,KreisLang,QuarSort,QuarCd,QuarLang,Ziv2Sort,Ziv2Cd,Ziv2Lang,AnzBestWir
0,1993,0,0,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,12
1,1993,0,0,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,14
2,1993,1,1,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,13
3,1993,1,1,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,11
4,1993,2,2,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
562324,2022,97,97,20,95,95-99,10,90,90-99,5,...,weiblich,12,Kreis 12,123,123,Hirzenbach,4,4,Verwitwet,5
562325,2022,98,98,20,95,95-99,10,90,90-99,5,...,weiblich,12,Kreis 12,123,123,Hirzenbach,2,2,Verheiratet,1
562326,2022,98,98,20,95,95-99,10,90,90-99,5,...,weiblich,12,Kreis 12,123,123,Hirzenbach,4,4,Verwitwet,1
562327,2022,99,99,20,95,95-99,10,90,90-99,5,...,weiblich,12,Kreis 12,123,123,Hirzenbach,4,4,Verwitwet,3
562328,2022,100,100,21,100,100 u. älter,11,100,100 u. älter,6,...,männlich,12,Kreis 12,123,123,Hirzenbach,4,4,Verwitwet,1

In [9]:
zurich_popul_ytd = zurich_popul.loc[
    zurich_popul["StichtagDatJahr"]
    == zurich_popul["StichtagDatJahr"].max()
]
zurich_popul_ytd = zurich_popul_ytd.dropna()
zurich_popul_ytd.head(10)

# Event year (technically: key date date year)	Year (integer).
# Age (Sort) (technically: AlterVSort)	Age (integer).
# Age (Cd) (technically: AlterVCd)	Age (integer, code).
# 5-year age group (Sort) (technically: AlterV05Sort)	Sorting key for age group (Numeric).
# 5-year age group (code) (technical: AlterV05Cd)	Age Group Code (Numeric).
# 5-year age group (technically: AlterV05Kurz)	5 year age group (e.g. 0-4, 5-10, etc.)
# 10-year age group (Sort) (technically: AlterV10Sort)	Sorting key for age group (Numeric).
# 10-year age group (code) (technically: AlterV10Cd)	Age Group Code (Numeric).
# 10-year age group (technically: AlterV10Kurz)	10 year age group (e.g. 0-9, 10-19, etc.)
# 20-year age group (Sort) (technically: AlterV20Sort)	Sorting key for age group (Numeric).
# 20-year age group (code) (technically: AlterV20Cd)	Age Group Code (Numeric).
# 20-year age group (technically: AlterV20Kurz)	20-year age group (e.g. 0-19, 20-29, etc.)
# Gender (Code) (technically: SexCd)	Gender (string).
# Gender (long) (technically: SexLang)	Gender (string).
# City district (code) (technically: KreisCd)	City circle (integer, code).
# City circle (long) (technically: KreisLang)	Urban district (string).
# City quarter (sort) (technically: QuarSort)	City quarter (Integer).
# City quarter (code) (technical: QuarCd)	City quarter (integer, code).
# City quarter (long) (technically: QuarLang)	City quarter (String).
# Civil status (grouped) (Sort) (technically: Ziv2Sort)	Civil status, sorting key of the group (integer).
# Civil status (grouped) (code) (technical: Ziv2Cd)	Civil status, group code (integer).
# Civil status (grouped) (Lang) (technically: Ziv2Lang)	Civil status grouped. (Values: 1 - Single, 2 - Married, 3 - Divorced, 4 - Widowed, 5 - In a registered partnership, 6 - In a dissolved partnership, 9 - Unknown).
# Economic population (technically: AnzBestWe)	Economic Population (Integer).

# https://data.stadt-zuerich.ch/dataset/bev_bestand_jahr_quartier_zivilstand_ag_geschl_od3310

,StichtagDatJahr,AlterVSort,AlterVCd,AlterV05Sort,AlterV05Cd,AlterV05Kurz,AlterV10Sort,AlterV10Cd,AlterV10Kurz,AlterV20Sort,...,SexLang,KreisCd,KreisLang,QuarSort,QuarCd,QuarLang,Ziv2Sort,Ziv2Cd,Ziv2Lang,AnzBestWir
542896,2022,0,0,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,8
542897,2022,0,0,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,6
542898,2022,1,1,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,5
542899,2022,1,1,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,9
542900,2022,2,2,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,4
542901,2022,2,2,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,7
542902,2022,3,3,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,9
542903,2022,3,3,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,6
542904,2022,4,4,1,0,0-4,1,0,0-9,1,...,männlich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,4
542905,2022,4,4,1,0,0-4,1,0,0-9,1,...,weiblich,1,Kreis 1,11,11,Rathaus,1,1,Ledig,9

In [74]:
zurich_popul_ytd_sum = (
    zurich_popul_ytd.groupby(["QuarLang", 
                              "SexLang", 
                              "Ziv2Lang"
                             ])
    .agg("sum")
    .reset_index()
)

civil_dict = {
    'Ledig': 'Single', 
    'Verheiratet': 'Married', 
    'Geschieden': 'Divorced', 
    'Unbekannt': 'Unknown',
    'In eingetragener Partnerschaft': 'In registered partnership', 
    'Aufgelöste Partnerschaft': 'Dissolved partnership',
    'Verwitwet': 'Widowed'
}

gender_dict = {"männlich": "Male", "weiblich": "Female"}

# zurich_popul_ytd_sum = zurich_popul_ytd_sum.replace(
#     {"Ziv2Lang": civil_dict}
# )

zurich_popul_ytd_sum = zurich_popul_ytd_sum.replace({"SexLang": gender_dict})
zurich_popul_ytd_sum = zurich_popul_ytd_sum.replace({"Ziv2Lang": civil_dict})

zurich_popul_ytd_sum.drop(['StichtagDatJahr', 'AlterVSort', 'AlterVCd',
       'AlterV05Sort', 'AlterV05Cd', 'AlterV10Sort', 'AlterV10Cd',
       'AlterV20Sort', 'AlterV20Cd', 'SexCd', 'KreisCd', 'QuarSort', 'QuarCd',
       'Ziv2Sort', 'Ziv2Cd'], inplace=True, axis=1, errors='ignore')

zurich_popul_ytd_sum

        QuarLang SexLang                   Ziv2Lang  AnzBestWir
0      Affoltern    Male      Dissolved partnership          16
1      Affoltern    Male                   Divorced         777
2      Affoltern    Male  In registered partnership          37
3      Affoltern    Male                     Single        7630
4      Affoltern    Male                    Unknown           2
..           ...     ...                        ...         ...
433  Wollishofen  Female  In registered partnership          19
434  Wollishofen  Female                     Single        5629
435  Wollishofen  Female                    Unknown           2
436  Wollishofen  Female                    Married        3319
437  Wollishofen  Female                    Widowed         570

[438 rows x 4 columns]

In [78]:
zurich_popul_ytd_sum = (
    zurich_popul_ytd_sum.groupby(["QuarLang", 
                              "SexLang"
                             ])
    .agg("sum")
    .reset_index()
)

zurich_popul_ytd_sum

        QuarLang SexLang  AnzBestWir
0      Affoltern  Female       13432
1      Affoltern    Male       13503
2    Albisrieden  Female       11601
3    Albisrieden    Male       11274
4   Alt-Wiedikon  Female        8819
..           ...     ...         ...
63     Wipkingen    Male        8259
64       Witikon  Female        6137
65       Witikon    Male        5265
66   Wollishofen  Female       10610
67   Wollishofen    Male        9960

[68 rows x 3 columns]